import Head from 'next/head'
import { useRef } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Image from 'next/image'
import { storageService } from '@/services/storage.service'
import c1 from '../../public/assets/images/c1.jpeg'
import c2 from '../../public/assets/images/c2.jpeg'
import c3 from '../../public/assets/images/c3.jpeg'
import c4 from '../../public/assets/images/c4.jpeg'
export default function Home() {
  const router = useRouter();
  // router.push('/auth/login')
  var is_chrome = /chrome/i.test( navigator.userAgent );
  if(!is_chrome) {
    router.push('/warn/chrome')
  }
  const formData = {
    password: useRef(),
    email: useRef()
  }
  let userString = storageService.get('user')

  if (userString) {
    let user = JSON.parse(userString)
    if (storageService.checkRole(user.role_id) == 'Administrator') {
      router.push('/administrator')
    }
  }
  const locate = () => {

    var options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };

    function success(pos) {
      var crd = pos.coords;

      // console.log('Your current position is:');
      // console.log(`Latitude : ${crd.latitude}`);
      // console.log(`Longitude: ${crd.longitude}`);
      // console.log(`More or less ${crd.accuracy} meters.`);
      alert('Your current position is : Latitude ' + crd.latitude + ' Longitude: ' + crd.longitude + ' More or less: crd.accuracy' + ' Meters')
      document.getElementById('locate').value = 'ok';
    };

    function error(err) {
      // alert('errr')
      alert(`ERROR(${err.code}): ${err.message}`);
    };

    navigator.geolocation.getCurrentPosition(success, error, options);
  }
  function detectMob() {
    const toMatch = [
      /Android/i,
      /webOS/i,
      /iPhone/i,
      /iPad/i,
      /iPod/i,
      /BlackBerry/i,
      /Windows Phone/i
    ];

    return toMatch.some((toMatchItem) => {
      return navigator.userAgent.match(toMatchItem);
    });
  }
 
  return (
    <>
      <Head>
        <title>{process.env.APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon/favicon-16x16.png" />
      </Head>
      <main>
        <div className='h-screen w-screen'>
          <div className="navbar bg-base-100 shadow-lg">
            <div className="navbar-start">
              <Image src={'/favicon/android-icon-144x144.png'} width={65} height={65} alt='favicon' />
            </div>
            <div className="navbar-center">
              <a className="btn btn-ghost normal-case font-bold text-sky-500 text-xl md:text-3xl lg:text-3xl">{process.env.APP_NAME}</a>
            </div>
            <div className="navbar-end">
              <Link href={'/auth/register'}>
                <button className='btn  btn-info mr-3'>
                  Daftar
                </button>
              </Link>
              <Link href={'/auth/login'}>
                <button className='btn btn-outline btn-info mr-3'>
                  Masuk
                </button>
              </Link>
            </div>
          </div>

          <section className='bg-base-100 mt-5'>
            {/* <button className='btn' onClick={() => locate()}>
              locate
            </button>
            <input type="text" disabled id='locate' /> */}
            <div className='px-3 md:px-0 lg:px-0'>
              
              <h1 className='text-4xl text-center font-bold mb-4 mt-3'>{process.env.APP_NAME}</h1>
              <p className='text-center text-xl max-w-3xl mx-auto'>
              Hasil kolaborasi Pemerintah Kota Sukabumi dengan Indosat.
              </p>
              <div className="flex w-full justify-center mt-3">
                <div className="carousel w-80 shadow-xl border border-gray-300">
                  <div id="item1" className="carousel-item w-80">
                    <Image width={'100%'} src={c1} alt='c1'></Image>
                  </div>
                  <div id="item2" className="carousel-item w-full">
                    <Image src={c2} alt='c1'></Image>
                  </div>
                  <div id="item3" className="carousel-item w-full">
                    <Image src={c3} alt='c1'></Image>
                  </div>
                  <div id="item4" className="carousel-item w-full">
                    <Image src={c4} alt='c1'></Image>
                  </div>
                </div>
              </div>
              <div className="flex justify-center w-full py-2 gap-2">
                <a href="#item1" className="btn btn-xs">1</a>
                <a href="#item2" className="btn btn-xs">2</a>
                <a href="#item3" className="btn btn-xs">3</a>
                <a href="#item4" className="btn btn-xs">4</a>
              </div>
              
            </div>
            <h1 className='text-4xl text-center font-bold mb-4 mt-5'>Layanan {process.env.APP_NAME}</h1>
            <div className='grid grid-cols-1 md:grid-cols-3 lg:grid-cols-3 gap-3 px-3 md:px-0 lg:px-0'>
              <div className='rounded-xl p-3 shadow-xl border border-gray-200 bg-base-100 flex flex-col items-center'>
                <Image src={'/assets/images/daily-report.png'} width={100} height={100} alt='poto' />
                <h2 className='text-2xl font-bold py-4'>E-Kinerja</h2>
                <p className='text-center text-lg'>E-Kinerja {process.env.APP_NAME} adalah layanan untuk monitoring dan evaluasi kinerja TPK di Kota Sukabumi.</p>
              </div>
              <div className='rounded-xl p-3 shadow-xl border border-gray-200 bg-base-100 flex flex-col items-center'>
                <Image src={'/assets/images/school.png'} width={100} height={100} alt='poto' />
                <h2 className='text-2xl font-bold py-4'>Dashboard</h2>
                <p className='text-center text-lg'>Layanan Dashboard {process.env.APP_NAME} merupakan layanan untuk pemetaan lokasi TPk serta grafik E-kinerja </p>
              </div>
              <div className='rounded-xl p-3 shadow-xl border border-gray-200 bg-base-100 flex flex-col items-center'>
                <Image src={'/assets/images/growth.png'} width={100} height={100} alt='poto' />
                <h2 className='text-2xl font-bold py-4'>Rekap Data</h2>
                <p className='text-center text-lg'>Layanan Rekap Data {process.env.APP_NAME} merupakan layanan rekapitulasi data TPK berdasarkan beberapa kategori</p>
              </div>
            </div>

          </section>

          <footer className="footer p-10 bg-neutral text-neutral-content">
            <div>
              <Image src={'/favicon/android-icon-144x144.png'} width={90} height={90} alt='favicon' />
              <p>{process.env.APP_NAME}<br />Jl. Kenari No.1A, Selabatu, Kec. Cikole, Kota Sukabumi, Jawa Barat 43114</p>
            </div>
            {/* <div>
              <span className="footer-title">Social</span>
              <div className="grid grid-flow-col gap-4">
                <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a>
                <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
                <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
              </div>
            </div> */}
          </footer>
        </div>
      </main>
    </>
  )
}
